### PR TITLE
Add support for qt6

### PR DESCRIPTION
**Pull request by Kasper24**
The dependencies list will need to be updated as well

### CODE REVIEW

**Comment by Kangie** [comment]
Hi! This isn't my code and I'm not updating it (I just needed somewhere to add tags for packaging at one point).

I did fork this theme and add some fixes - I would welcome such a PR there: https://gitlab.com/Matt.Jolly/sddm-eucalyptus-drop 

Edit: Accidentally closed it off early.

**Comment by kie4280** [comment]
Is this merged yet?

**Comment by Kangie** [comment]
I am not updating this code. It's not mine. I have a fork linked above which has some fixes. Please submit a PR there. :)

**Comment by Kangie** [comment]
Merged here: https://gitlab.com/Matt.Jolly/sddm-eucalyptus-drop/-/commit/c29d518ee5098cc05458b80ccf5a83c2a9822d57

**Pull request closed without merging**
